version: "3.1"

services:
  pizzeria-app:
    depends_on:
      - db
    build:
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "9090:9090"

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=@MYSQL_USER
      - MYSQL_PASSWORD=@MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - pizzadb:/var/lib/mysql

volumes:
  pizzadb:
